DELETE http://localhost:3001/api/persons/15199

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "John Doe",
    "number": "555-9955"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Harry Mcree",
    "number": "777-99887"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Harry Mcree"    
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "New Dan Abramov",
    "number": "0123-8899"    
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "New Dan Steward",
    "number": "0123-8899"    
}